services:
  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: maristmaps
      POSTGRES_PASSWORD: maristmaps
      POSTGRES_DB: maristmaps
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-postgis.sql:/docker-entrypoint-initdb.d/01-init-postgis.sql

  martin:
    image: ghcr.io/maplibre/martin:1.5.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://maristmaps:maristmaps@db:5432/maristmaps
    volumes:
      - ./martin:/config
    depends_on:
      - db
    command: --config /config/config.yaml

volumes:
  postgres_data:
